language: ruby
rvm:
 - 2.2
sudo: required
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - rake:db drop rake:db create rake:db migrate
